In [101]:
# load all pickle files in a directory (all of them are lists)

import pickle
import pathlib
import numpy as np

In [102]:
def load_pickle_files(path):
    pathlist = pathlib.Path(path).glob('*.pkl')
    list_of_lists = []
    for path in sorted(pathlist):
        path_in_str = str(path)
        print(path_in_str)
        with open(path_in_str, 'rb') as f:
            list_of_lists.append(pickle.load(f))
    return list_of_lists

# replace zero at the end of the array with last non zero value
def replace_zeros(arr):
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            if arr[i][j] == 0:
                arr[i][j] = arr[i][j-1]
    return arr

In [103]:
data = load_pickle_files('/home/rudra/Desktop/markov_models/synthetic_joystic/recorded')

/home/rudra/Desktop/markov_models/synthetic_joystic/recorded/attentive.pkl
/home/rudra/Desktop/markov_models/synthetic_joystic/recorded/left_bias.pkl
/home/rudra/Desktop/markov_models/synthetic_joystic/recorded/rebel.pkl
/home/rudra/Desktop/markov_models/synthetic_joystic/recorded/top_bias.pkl


In [104]:
target_angles = []
for files in data: target_angles.append(files[-1][:, 0])

In [105]:
target_angles = np.array(target_angles)
target_angles

array([[ 47.63350621, 126.13505974, 304.35863703, 229.73362297,
          4.12979537, 317.10494267,  47.60077305, 227.48687995,
        181.55450061, 133.27525528, 297.77833861, 329.79318325,
         88.69721678, 307.82421182, 356.68681174, 177.42785519,
        198.43095836, 219.22420868, 317.33350397, 359.22611964],
       [119.02205865,  33.88335166, 268.38503178,  71.10400744,
        343.15929477,  31.84747105, 251.92030748, 268.15952462,
        280.958378  , 112.65937743, 272.51677652, 256.07237399,
         38.01935833, 138.41207972, 126.64988314, 279.23287102,
        150.77749463, 207.56735157, 289.45607619, 186.02720236],
       [164.38885618, 133.86480524, 232.38302683, 307.25247308,
        351.98388737, 229.12247434, 255.25732502, 286.9473308 ,
        120.91912885, 252.2998257 , 345.24050978, 123.8264796 ,
         49.69239565, 228.38904533,  88.42609823, 347.40237226,
        160.92140108,  40.25570246, 341.73207653, 154.96872532],
       [ 45.62339569, 141.2569898 , 3

In [106]:
cursor_angles = []
for files in data: cursor_angles.append(files[-2][:, :, 0])
cursor_angles = np.array(cursor_angles)
cursor_angles.shape

(4, 20, 1300)

In [107]:
cursor_angles = replace_zeros(cursor_angles.reshape(-1, 1300)).reshape(4, 20, 1300)[:,:, -1]

In [108]:
cursor_angles

array([[ 47.96974843, 125.70308085, 304.24903301, 229.47665875,
          4.20961106, 317.00955381,  47.33110748, 227.63011266,
        182.24025735, 133.09418862, 297.72498721, 329.95111773,
         88.71106244, 307.67359334, 356.72545315, 177.11600089,
        198.66321765, 219.30959565, 317.23380926, 359.26922611],
       [177.84163287, 178.14779689, 177.69789171, 177.84703721,
        178.69804733, 179.44374777, 180.14432156, 180.        ,
        186.46176491, 180.58314301, 178.29864539, 176.67594923,
        178.23760898, 179.13847427, 176.45898433, 178.53868991,
        180.57726792, 178.54610453, 178.85136634, 180.28791607],
       [344.563073  , 309.56452231,  49.91097585, 140.3185127 ,
        179.14744716,  47.16107949,  75.65066796, 115.2239234 ,
        311.74112569,  78.69006753, 173.51360443, 301.55138495,
        233.41586447,  47.1210964 , 265.15359517, 166.06724067,
        341.06762597, 228.89584801, 154.14147531, 336.1673024 ],
       [273.60328864, 271.16320625, 2

In [109]:
cursor_angles.shape

(4, 20)

In [110]:
# for 4 subjects, we have 20 trials

# for each of the subjects
# randomly sample 100 trials with same index of target and cursor angles
# choose a random degree between -10 and +10
# add that degree to the cursor angle and target angle
# save the new cursor angle and target angle in a new list

aug_cursor = []
aug_target = []

for i in range(4):
    t_cursor = []
    t_target = []
    for x in range(100):
        # sample a random index
        index = np.random.randint(0, 20)
        # sample a random degree
        degree = np.random.randint(-10, 10)
        # add the degree to the cursor angle and target angle
        t_cursor.append(cursor_angles[i][index] + degree)
        t_target.append(target_angles[i][index] + degree)
    
    aug_cursor.append(t_cursor)
    aug_target.append(t_target)

aug_cursor = np.array(aug_cursor)
aug_target = np.array(aug_target)

# make them 2 decimal places
aug_cursor = np.round(aug_cursor, 2)
aug_target = np.round(aug_target, 2)

In [111]:
aug_cursor

array([[134.09, 229.63, 359.27, 130.7 , 288.72, 309.25, 227.48, 323.23,
        322.23,  81.71, 313.67, 309.23, 321.23, 323.95, 314.67, 338.95,
         56.97, 127.09, 236.48, 173.24, 314.67,  89.71, 360.27, 175.24,
        294.72,  48.33, 322.01, 351.27, 355.27, 354.73, 229.48, 309.25,
        182.24,   8.21,  46.33, 188.24, 357.73, 307.67, 309.67, 228.48,
        289.72, 301.25, 177.12, 319.01,   9.21,  -0.79, 220.48, 359.27,
        172.24, 221.31,  12.21, 235.48, 238.48, 301.72, 226.48, 308.25,
        297.67, 360.27, 356.27, 224.31, 226.63, 222.63,  53.97, 363.73,
        295.72, 313.67, 218.63, 356.27, 306.67, 297.25, 180.24, 130.7 ,
        311.01, 350.73, 320.01,  55.33, 361.27, 310.01, 180.12, 129.09,
        228.31, 297.72, 321.01, 123.7 ,  86.71,  13.21,  86.71, 321.23,
        309.23,  42.97, 228.63,  10.21, 125.7 , 190.24, 316.01,  -5.79,
        297.25,  11.21,  -1.79, 314.01],
       [186.  , 179.54, 172.58, 182.7 , 177.85, 186.44, 175.24, 177.46,
        168.84, 182.54,

In [112]:
# Now make the augmented data cursor and target angles into format of 10 of 1st suject, 10 of second subject and so on
# making it 40 of 4 total subjects
# save that into new variable

In [120]:
ch_cursor = [aug_cursor[:, i:i+10].reshape(-1) for i in range(10)]
ch_target = [aug_target[:, i:i+10].reshape(-1) for i in range(10)]
ch_cursor = np.array(ch_cursor)
ch_target = np.array(ch_target)

In [122]:
ch_cursor.shape, ch_target.shape

((10, 40), (10, 40))

In [127]:
n = 4
ch_cursor[n], ch_target[n]

(array([288.72, 309.25, 227.48, 323.23, 322.23,  81.71, 313.67, 309.23,
        321.23, 323.95, 177.85, 186.44, 175.24, 177.46, 168.84, 182.54,
        183.85, 175.46, 187.58, 180.14, 303.56, 309.55, 109.22,  82.65,
        301.55, 161.07, 169.15, 341.17, 268.15, 135.32, 261.58, 273.36,
        270.86, 271.36, 268.56, 263.86, 261.36, 261.9 , 269.6 , 271.85]),
 array([288.78, 309.36, 227.73, 323.33, 322.33,  81.7 , 313.82, 309.33,
        321.33, 323.79,  71.1 ,  38.85,  35.02, 127.65, 110.02, 283.23,
        294.46, 125.65, 157.78, 251.92, 127.86, 131.83, 280.95, 262.26,
        123.83, 342.4 , 341.98, 159.97,  91.43, 302.25, 341.46, 248.66,
        333.64, 246.66, 319.28, 326.64, 236.66, 265.03, 338.81, 248.05]))

In [128]:
np.save('ch_cursor.npy', ch_cursor)
np.save('ch_target.npy', ch_target)