In [1]:
from scipy.io import loadmat
from scipy.stats import circmean, circstd
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Set in stone
data_path = './axej_eeg/'
n_subjects = 13
n_sessions = 4
n_runs = 1
n_trials = 120
n_ts = 500

exp_ts = 1000

# noise frames = 0 to 220 (250 - 30)
noise_thresh = 0.5
noise_gap = 30


experiment_orientations = [159, 123, 87, 51, 15]
subjects = ["01", "02", "03", "04", "05", "06", "07", "08" ,"09", "10", "11", "12", "14"]

def get_calib(subj, sess):
    mat_contents = loadmat(data_path + f'AxeJEEG_Subj{subjects[subj]}_S{sess+1}_Cali1.mat.mat', struct_as_record=False, squeeze_me=True)
    return mat_contents["p"].__dict__

def get_run(subj, sess, run):
    mat_contents = loadmat(data_path + f'AxeJEEG_Subj{subjects[subj]}_S{sess+1}_Run{run+1}.mat.mat', struct_as_record=False, squeeze_me=True)
    return mat_contents["p"].__dict__

In [22]:
df = get_calib(subj=1, sess=1)

for key in df.keys():
    print(key, np.array(df[key]).shape)

_fieldnames (34,)
exptName ()
subName ()
sessionNum ()
runNum ()
rndSeed ()
EEG ()
ori (5,)
alloriTag (5,)
tgCoh (120,)
attCue (120,)
cueColor (120,)
tgColor (120,)
stimDir (120,)
stimDirReal (120,)
stimDirREAL (120,)
tnumb ()
fdur (120, 500)
joyx (120, 500)
joyy (120, 500)
f_precuedur (120,)
f_cuedur (120,)
f_tgdur (120,)
f_nontgdur (120,)
f_ITIdur (120,)
stimonset (120,)
cueonset (120,)
SCI (120,)
tgonset (120,)
CTI (120,)
tgoffset (120,)
tgDur (120,)
stimoffset (120,)
stimDur (120,)
ITI (120,)


In [26]:
df["f_precuedur"] + df["f_cuedur"]

array([156, 204, 192, 180, 180, 156, 156, 168, 144, 132, 216, 156, 168,
       156, 180, 156, 216, 192, 180, 120, 156, 168, 204, 144, 168, 204,
       132, 156, 144, 180, 168, 168, 216, 168, 144, 156, 168, 168, 180,
       168, 144, 156, 204, 132, 204, 120, 144, 204, 156, 132, 180, 156,
       144, 156, 144, 168, 132, 156, 168, 168, 168, 132, 168, 132, 192,
       168, 192, 192, 168, 132, 132, 168, 180, 180, 156, 192, 156, 168,
       204, 144, 168, 192, 204, 168, 168, 192, 156, 132, 132, 132, 204,
       192, 156, 120, 180, 156, 156, 216, 144, 180, 168, 168, 192, 168,
       132, 156, 144, 168, 156, 216, 216, 180, 192, 216, 156, 144, 156,
       204, 192, 132], dtype=uint8)

In [27]:
df["f_precuedur"]

array([60, 96, 96, 72, 60, 60, 84, 60, 60, 48, 96, 48, 84, 72, 84, 84, 96,
       96, 60, 48, 48, 60, 84, 48, 84, 84, 48, 48, 48, 96, 48, 84, 96, 60,
       48, 72, 96, 48, 84, 72, 72, 60, 96, 48, 84, 48, 48, 84, 72, 60, 96,
       72, 48, 60, 60, 60, 48, 84, 48, 96, 72, 48, 60, 60, 84, 72, 96, 72,
       72, 60, 48, 72, 96, 84, 84, 84, 72, 96, 84, 60, 48, 84, 84, 96, 84,
       72, 84, 48, 60, 60, 84, 72, 84, 48, 60, 48, 84, 96, 48, 60, 60, 96,
       72, 84, 60, 60, 48, 84, 84, 96, 96, 60, 96, 96, 60, 72, 48, 96, 72,
       60], dtype=uint8)

In [28]:
df["f_cuedur"]

array([ 96, 108,  96, 108, 120,  96,  72, 108,  84,  84, 120, 108,  84,
        84,  96,  72, 120,  96, 120,  72, 108, 108, 120,  96,  84, 120,
        84, 108,  96,  84, 120,  84, 120, 108,  96,  84,  72, 120,  96,
        96,  72,  96, 108,  84, 120,  72,  96, 120,  84,  72,  84,  84,
        96,  96,  84, 108,  84,  72, 120,  72,  96,  84, 108,  72, 108,
        96,  96, 120,  96,  72,  84,  96,  84,  96,  72, 108,  84,  72,
       120,  84, 120, 108, 120,  72,  84, 120,  72,  84,  72,  72, 120,
       120,  72,  72, 120, 108,  72, 120,  96, 120, 108,  72, 120,  84,
        72,  96,  96,  84,  72, 120, 120, 120,  96, 120,  96,  72, 108,
       108, 120,  72], dtype=uint8)

In [25]:
df["tgonset"] - df["tgonset"][0]

array([  0.        ,   4.00026484,   7.60050928,  11.23408841,
        14.9260121 ,  18.28456633,  21.60979259,  25.11836421,
        28.41025298,  31.80214888,  35.61073963,  39.04430898,
        42.42787114,  45.82810162,  49.51168375,  52.8702458 ,
        56.7538419 ,  60.47076123,  64.1126741 ,  67.35455959,
        70.77146146,  74.45504303,  78.30530445,  81.54718994,
        85.05576239,  88.94769307,  92.02290123,  95.43146685,
        98.6900201 , 102.24026238, 105.88217497, 109.34074414,
       113.14100088, 116.69957495, 120.01646774, 123.45836831,
       127.04194388, 130.55884896, 134.20076239, 137.61766062,
       141.05959277, 144.52646356, 148.35172319, 151.65194683,
       155.60221537, 158.79409869, 162.11932438, 165.87791214,
       169.46982284, 172.84505154, 176.59530639, 180.15388101,
       183.47912542, 186.94603895, 190.18789539, 193.69646533,
       196.90501642, 200.17190621, 203.57214199, 207.05570652,
       210.69763699, 213.87283328, 217.49808202, 220.71

In [29]:
df = get_run(subj=3, sess=2, run=2)

for key in df.keys():
    print(key, np.array(df[key]).shape)

_fieldnames (37,)
exptName ()
subName ()
sessionNum ()
runNum ()
rndSeed ()
EEG ()
ori (5,)
alloriTag (5,)
tgCoh (120,)
attCue (120,)
cueColor (120,)
tgColor (120,)
expOri ()
unexpOri (4,)
stimDir (120,)
stimDirReal (120,)
stimDirREAL (120,)
tnumb ()
fdur (120, 500)
timeeachframe (120, 500)
joyx (120, 500)
joyy (120, 500)
f_precuedur (120,)
f_cuedur (120,)
f_tgdur (120,)
f_nontgdur (120,)
f_ITIdur (120,)
stimonset (120,)
cueonset (120,)
SCI (120,)
tgonset (120,)
CTI (120,)
tgoffset (120,)
tgDur (120,)
stimoffset (120,)
stimDur (120,)
ITI (120,)


In [37]:
1/120 * 6

0.05

In [36]:
4000/500

8.0

In [31]:
df["timeeachframe"][0]

array([0.05096039, 0.06333012, 0.07194993, 0.07969393, 0.08807879,
       0.09635694, 0.10469347, 0.11302302, 0.12136123, 0.12969553,
       0.1380519 , 0.14639095, 0.15472106, 0.16306765, 0.17136284,
       0.17974743, 0.1880292 , 0.1963649 , 0.20469278, 0.21303099,
       0.22135886, 0.22973199, 0.23813529, 0.24636846, 0.25470304,
       0.26302868, 0.27136913, 0.27970035, 0.28804192, 0.29636336,
       0.30470912, 0.31303196, 0.32137381, 0.32970308, 0.33803961,
       0.34637084, 0.35470765, 0.3630386 , 0.37137597, 0.37970943,
       0.38803814, 0.39637691, 0.40470479, 0.41304412, 0.42140412,
       0.43006751, 0.43804115, 0.44638159, 0.45470835, 0.46305997,
       0.47137583, 0.47971795, 0.48804583, 0.49638404, 0.50483455,
       0.51304845, 0.52138861, 0.52971258, 0.53805302, 0.54638117,
       0.55558011, 0.56305145, 0.5713905 , 0.57971753, 0.58805742,
       0.59638529, 0.60472351, 0.61305278, 0.62142395, 0.63001052,
       0.63805651, 0.64639584, 0.65472316, 0.66306416, 0.67139

In [21]:
ft = df["fdur"][3]
np.cumsum(ft)

array([0.00096157, 0.00144264, 0.00190778, 0.00236678, 0.00283248,
       0.00329148, 0.00375551, 0.00421422, 0.00467825, 0.00513808,
       0.00560239, 0.00606083, 0.00652681, 0.0069872 , 0.00771998,
       0.00817897, 0.00865166, 0.00911485, 0.00957608, 0.01007866,
       0.01053961, 0.01100363, 0.01146207, 0.01192721, 0.01238705,
       0.01285247, 0.01331091, 0.01377605, 0.01423589, 0.01470103,
       0.01516059, 0.01563187, 0.01609646, 0.01657445, 0.01703904,
       0.01749887, 0.01796318, 0.01842273, 0.01915132, 0.01961059,
       0.02007574, 0.02053613, 0.02100016, 0.02145999, 0.02192485,
       0.02238776, 0.02285765, 0.0233228 , 0.02378347, 0.02424805,
       0.02477801, 0.02524399, 0.02570466, 0.02616841, 0.02662797,
       0.02709227, 0.02755155, 0.02801529, 0.02847373, 0.02893915,
       0.02939927, 0.02986916, 0.03036671, 0.03082682, 0.03129308,
       0.03175404, 0.03221834, 0.03267818, 0.0331422 , 0.03360315,
       0.03406634, 0.03452841, 0.03553049, 0.03599089, 0.03645

In [3]:
# Get all run data
# subjexts x sessions x runs
jx = []
jy = []
stimdir = []
tgonset = []

# Attention (attCue): tr_foc = 1, tr_div = 2
# Coherence (tgCoh): tr_lo = 1, tr_hi = 2
att = []
coh = []

for subj in tqdm(range(n_subjects)):
    for sess in range(n_sessions):
        for run in range(n_runs):

            data = get_calib(subj, sess)
            jx.append(data["joyx"])
            jy.append(data["joyy"])
            stimdir.append(data["stimDirREAL"])

            f_tgonset = data["f_precuedur"] + data["f_cuedur"]
            tgonset.append(f_tgonset)

            att.append(data["attCue"])
            coh.append(data["tgCoh"])

# Shape the run data
jx = np.array(jx, dtype=np.float64).reshape(n_subjects, n_sessions, n_runs, n_trials, n_ts)
jy = np.array(jy, dtype=np.float64).reshape(n_subjects, n_sessions, n_runs, n_trials, n_ts)
stimdir = np.array(stimdir).reshape(n_subjects, n_sessions, n_runs, n_trials)
tgonset = np.array(tgonset).reshape(n_subjects, n_sessions, n_runs, n_trials)
att = np.array(att).reshape(n_subjects, n_sessions, n_runs, n_trials)
coh = np.array(coh).reshape(n_subjects, n_sessions, n_runs, n_trials)

jx.shape, jy.shape, stimdir.shape, tgonset.shape

100%|██████████| 13/13 [00:00<00:00, 78.80it/s]


((13, 4, 1, 120, 500), (13, 4, 1, 120, 500), (13, 4, 1, 120), (13, 4, 1, 120))