In [1]:
# orientations (15-159° with 36° increments)
# - 15, 51, 87, 123, 159

# 50 sessions, 5 blocks, 20 trials each = 5000 trials

In [2]:
import numpy as np
rng = np.random.default_rng()

In [20]:
targets = np.array([[15, 51, 87, 123, 159]*4*5]*50)
targets = rng.permuted(targets, axis=1)
targetsn_1 = np.roll(targets, 1, axis=1)
targetsn_1[:,0] = 0

# np random floats from -3 to 3 of shape 50, 100
jitters = rng.uniform(-3, 3, size=(50, 100))
observations = targets + jitters
t = targetsn_1 + jitters
observations[:, -10:] = t[:, -10:]

observations.shape, targets.shape, targetsn_1.shape

((50, 100), (50, 100), (50, 100))

In [21]:
observations[0, :10], targets[0, :10], targetsn_1[0, :10]

(array([ 51.4946109 ,  14.05497273, 161.61593225,  14.56845713,
        122.62063208,  87.47965399,  88.1509385 ,  52.20394882,
         84.54767697,  15.82798113]),
 array([ 51,  15, 159,  15, 123,  87,  87,  51,  87,  15]),
 array([  0,  51,  15, 159,  15, 123,  87,  87,  51,  87]))